const users = [
  {
    email: 'admin@admin.com',
    password: 'admin',
  },
];

const series = [
  "Breaking Bad",
  "Game of Thrones",
  "The Wire",
  "Stranger Things",
  "The Crown",
  "Friends",
  "The Office",
  "Sherlock",
  "The Mandalorian",
  "The Witcher",
  "Fargo",
  "True Detective",
  "Westworld",
  "Mindhunter",
  "Black Mirror",
  "The Handmaid's Tale",
  "The Sopranos",
  "Better Call Saul",
  "Mad Men",
  "House of Cards",
  "Ozark",
  "Peaky Blinders",
  "The Boys",
  "The Umbrella Academy",
  "Succession",
  "Euphoria",
  "Chernobyl",
  "Killing Eve",
  "Brooklyn Nine-Nine",
  "Parks and Recreation"
];

const peliculas = [
  "The Godfather",
  "Titanic",
  "Pulp Fiction",
  "The Dark Knight",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Star Wars: Episode IV - A New Hope",
  "The Silence of the Lambs",
  "The Lion King",
  "Gladiator",
  "Back to the Future",
  "The Godfather: Part II",
  "Saving Private Ryan",
  "The Shawshank Redemption",
  "The Dark Knight Rises",
  "The Lord of the Rings: The Return of the King",
  "The Lord of the Rings: The Two Towers",
  "Forrest Gump",
  "The Avengers",
  "Jurassic Park",
  "Avatar",
  "The Great Gatsby",
  "Inglourious Basterds",
  "The Departed",
  "The Wolf of Wall Street",
  "The Grand Budapest Hotel",
  "Gone with the Wind",
  "Casablanca",
  "The Wizard of Oz",
  "Psycho",
  "The Shining",
  "Goodfellas",
  "Fight Club",
  "Inception",
  "The Usual Suspects",
  "The Terminator",
  "Alien",
  "The Godfather: Part III",
  "The Green Mile",
  "The Sixth Sense",
  "Schindler's List",
  "The Matrix",
  "Interstellar"
];

  module.exports = {peliculas, series, users};