const peliculas = [
    "The Godfather",
    "Titanic",
    "The Shawshank Redemption",
    "Pulp Fiction",
    "Forrest Gump",
    "The Dark Knight",
    "Schindler's List",
    "Inception",
    "The Matrix",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Fight Club",
    "Star Wars: Episode IV - A New Hope",
    "The Silence of the Lambs",
    "The Lion King",
    "Gladiator",
    "Back to the Future",
    "The Green Mile",
    "The Godfather: Part II",
    "The Departed",
    "Saving Private Ryan",
    "The Shawshank Redemption",
    "The Dark Knight Rises",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "Forrest Gump",
    "The Avengers",
    "Jurassic Park",
    "Avatar",
    "The Great Gatsby",
    "Inglourious Basterds",
    "The Departed",
    "The Wolf of Wall Street",
    "The Grand Budapest Hotel",
    "Gone with the Wind",
    "Casablanca",
    "The Wizard of Oz",
    "Psycho",
    "The Shining",
    "Goodfellas",
    "Fight Club",
    "Inception",
    "The Usual Suspects",
    "The Terminator",
    "Alien",
    "The Godfather: Part III",
    "The Green Mile",
    "The Sixth Sense",
    "Schindler's List",
    "The Matrix",
    "Interstellar"
  ];

  module.exports = {peliculas};